### ISSUE TITLE
3.1.0 should be breaking

### ISSUE THREAD

**Issue by smaren** [jaredwray/flat-cache#76]
Release version 3.1.0 removes support of Node 10 - this should be a breaking change. Can we get a bugfix version where Node 10 is supported?

**Comment by jaredwray** [comment]
@smaren this was a hard call to make and in the end we saw little to no users on it to make a major version shift. In the end we should do it and will plan to do it in the future. We did test it with v10 and only saw minor issues but were no longer able to perform all unit tests which is why we decided to do a minor release. 

Until then please set your version to 3 and you should be fine.
